### PR TITLE
Add pythonanywhere 0.10.2

### PR DESCRIPTION
**Pull request by skupr-anaconda**
License: https://github.com/pythonanywhere/helper_scripts/blob/master/LICENSE
Changelog: https://github.com/pythonanywhere/helper_scripts/releases
Requirements: https://github.com/pythonanywhere/helper_scripts/blob/v0.10.2/setup.py

Actions:
1. Add a new recipe

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
An error on `s390x`:
```
conda.exceptions.ResolvePackageNotFound:
  - docopt
```
We have to skip building on `s390x`

**Review by cbouss — COMMENTED** [review]
LGTM
Regarding skipping s390x instead of building docopt, I assume this is because running python anywhere from s390x doesn't serve much purpose.

**Comment by marcoesters** [comment]
> LGTM Regarding skipping s390x instead of building docopt, I assume this is because running python anywhere from s390x doesn't serve much purpose.

My suggestion is to add a comment on why `s390x` will be skipped and why building `docopt` for `s390x` was not done.

**Review by varlackc — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
@marcoesters @cbouss I've decided to rebuild `docopt` https://github.com/AnacondaRecipes/docopt-feedstock/pull/1

**Pull request merged**
